# Generated by Django 6.0.3 on 2026-04-10 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Cédula')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Destino')),
                ('ciudad_destino', models.CharField(max_length=100, verbose_name='Ciudad Destino')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('clima', models.CharField(max_length=50, verbose_name='Clima')),
                ('actividades', models.TextField(verbose_name='Actividades Disponibles')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL Imagen')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'Destinos',
            },
        ),
        migrations.CreateModel(
            name='Guias_Turisticos',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Guía')),
                ('nombre_guia', models.CharField(max_length=100, verbose_name='Nombre del Guía')),
                ('cedula_guia', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('anos_experiencia', models.PositiveIntegerField(verbose_name='Años de Experiencia')),
                ('idiomas', models.CharField(max_length=200, verbose_name='Idiomas')),
                ('certificado', models.BooleanField(default=False, verbose_name='Certificado')),
            ],
            options={
                'verbose_name': 'Guía Turístico',
                'verbose_name_plural': 'Guías Turísticos',
                'db_table': 'Guias_Turisticos',
            },
        ),
        migrations.CreateModel(
            name='Paquetes_Turisticos',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Paquete')),
                ('nombre_paquete', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('duracion_dias', models.PositiveIntegerField(verbose_name='Duración (Días)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('incluye', models.TextField(verbose_name='Incluye')),
                ('no_incluye', models.TextField(verbose_name='No Incluye')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='Capacidad Máxima')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo_django.destinos', verbose_name='Destino')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turismo_django.guias_turisticos', verbose_name='Guía Asignado')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'db_table': 'Paquetes_Turisticos',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_inicio_viaje', models.DateField(verbose_name='Fecha Inicio Viaje')),
                ('fecha_fin_viaje', models.DateField(verbose_name='Fecha Fin Viaje')),
                ('numero_personas', models.PositiveIntegerField(verbose_name='Número de Personas')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo_django.clientes', verbose_name='Cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo_django.paquetes_turisticos', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reservas',
            },
        ),
    ]
